### PR TITLE
Fix using key array with one item

### LINKED ISSUE #37: Issue when calling Model.get with an array with a length of 1
If you call the `Model.get` method with an array consisting of only one ID, nothing seems to be returned.

For example, calling the following returns an array of 2 entities:

```js
MyModel.get([10, 15])
```

However calling the following doesn't return anything:

```js
MyModel.get([10])
```

### PR DESCRIPTION
**Pull request by micaww**
Fixes #37

### CODE REVIEW

File: lib/model.js [hunk 1]
```diff
@@ -401,7 +401,7 @@ class Model extends Entity {
         const args = Array.prototype.slice.apply(arguments);
 
         cb = args.pop();
-        id = parseId(id);
+        id = multiple ? id.map(parseId) : parseId(id);
         ancestors = args.length > 1 ? args[1] : undefined;
```
Comment (sebelga) [inline lib/model.js]: test failed, because here multiple is not declared.
Can you add: `const multiple = is.array(id);` and squash into 1 commit?

**Comment by sebelga** [comment]
hi @micaww will you have some time for the fix or do you want me to have a look at it? thanks! :)
